---
- name: "Install common packages"
  apt: name={{ item }} state=present
  with_items:
    - wget
    - git
    - vim
    - htop
    - apache2
    - mysql-server
    - python-mysqldb
    - emacs
    - curl
    - wget
    - phpmyadmin

- name: "Installing PHP packages"
  apt: name={{ item }} state=present
  with_items:
    - php5
    - php5-cli
    - php5-curl
    - php5-intl
    - php5-gd
    - php5-mysql
  notify:
    - restart apache

- name: "Configuring PHP memory"
  action: ini_file dest=/etc/php5/apache2/php.ini section=global option=memory_limit value=256M mode=0600
  notify:
    - restart apache

- name: "Configuring PHP Timezone"
  action: ini_file dest=/etc/php5/apache2/php.ini section=Date option=date.timezone value=Europe/Paris mode=0600

- name: "Enable mod_rewrite"
  apache2_module: state=present name=rewrite
  notify:
    - restart apache

- name: "Enable mod_expires"
  apache2_module: state=present name=expires
  notify:
    - restart apache

- name: "Copying Virtualhost"
  sudo: yes
  template: src={{ template_source }} dest={{ vhost_destination }}/dropshippers.conf
  notify:
    - restart apache

#- name: "Configuring Virtualhost"
#  sudo: yes
#  replace: dest={{ vhost_destination }}/dropshippers.conf

- name: "Creating Dropshippers web Symlink"
  sudo: yes
  file: src={{ project_default_location }} dest={{ project_link }} state=link
  notify:
    - restart apache

- name: "Creating phpmyadmin web Symlink"
  sudo: yes
  file: src=/usr/share/phpmyadmin dest=/var/www/html/phpmyadmin state=link
  notify:
    - restart apache

- name: "enabling virtualhost"
  sudo: yes
  shell: a2ensite dropshippers
  notify:
    - restart apache

- name: "disable apache default site"
  sudo: yes
  shell: a2dissite 000-default
  notify:
      - restart apache

- name: "Installing composer"
  shell: curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin creates=/usr/local/bin/composer

- name: "Renaming composer.phar to composer"
  shell: mv /usr/local/bin/composer.phar /usr/local/bin/composer creates=/usr/local/bin/composer

- name: "Making composer executable"
  file: path=/usr/local/bin/composer mode=755 state=file

- name: "Installing pretissimo (faster composer)"
  shell: composer global require hirak/prestissimo

- name: "Creating dropshippers Database"
  mysql_db: name=dropshippers state=present

- name: "Creating MySQL dropshippers user"
  mysql_user: name=dropshippers password=P@ssword priv=*.*:ALL state=present

- name: "Resolving composer dependencies"
  command: composer install --no-interaction --prefer-dist --no-progress chdir={{ project_link }}

- name: "Installing Symfony database"
  command:  bin/console doctrine:schema:update --force chdir={{ project_link }}

- name: "Injecting DataFixtures"
  command:  bin/console doctrine:fixtures:load chdir={{ project_link }}

- name: "Installing aliases"
  template: src={{ project_default_location }}/ansible/roles/dropshippers/templates/bash_aliases.template dest=/home/vagrant/.bash_aliases
  when: ( dev == 1 )
