language: php
php:
    - 5.6
    - 7.1
services:
    - mysql
before_install:
    - echo "hello first test !"
    - mysql -e -uroot 'CREATE DATABASE IF NOT EXISTS dropshippers;'
    - mysql -e -uroot "CREATE USER 'dropshippers'@'localhost' IDENTIFIED BY 'P@ssword';"
    - mysql -e -uroot "GRANT ALL ON dropshippers.* To 'dropshippers'@'localhost';"

install:
    - composer install