language: php
php:
    - 5.6
    - 7.1
services:
    - mysql
before_install:
    - echo "hello first test !"
    - mysql -e 'CREATE DATABASE if not exists dropshippers;'
    - mysql -e "CREATE USER 'dropshippers'@'localhost' IDENTIFIED BY 'P@ssword';"
    - mysql -e "GRANT ALL ON dropshippers.* To 'dropshippers'@'localhost';"

install:
    - composer install