language: php

php:
  - 7.1

services:
  - mysql

addons:
  ssh_known_hosts:
    - 46.101.119.131

notifications:
  email: false

before_install:
  - echo "hello first test !"
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common sshpass
  - sudo rm /etc/ssh/ssh_config
  - sudo cp ansible/roles/dropshippers/templates/ssh_config /etc/ssh/ssh_config
  - sudo cat /etc/ssh/ssh_config
  - sudo cat ~/.ssh/config
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
#  - echo -e "$id_rsa.pub" > ~/.ssh/id_rsa.pub
#  - echo -e "$id_rsa" > ~/.ssh/id_rsa
  - echo -e "-----BEGIN RSA PRIVATE KEY-----\nProc-Type: 4,ENCRYPTED\nDEK-Info: AES-128-CBC,EC278AB2CC9E0B4A62A375D49103D606\nBIu6Rq0018mZmkaH886s3HX4HPigRG0BC8WDGAfwPNWjJ6jJ3iXDqJ+Asu4hRofm\nqf95goy+AEUpYPF8VHQpyC2SyvrIkELn3PBYtm5x6lGJel0dps4PjzFy3jT3W3ec\n2+PmVEMCwbryCeCJWoS7xSpUnQ1cD1qBqmLckoavTyQwF5FHcpVO5KVEww5WCgpB\nxp0OLrb6sOsDdXz750p0SXh1RUQW9019sCItMa8GZ/wrPeF89lzpkFyF4g99AvL9\n8e+j2hrxTNn/SBgheRsoKbMGOYrucJmow7PS6kGg7P9ur1EOEdCv85JvjCG7MhLV\nzZH0UvCW6ZNWdS/xltwEpfIriu2+mKKSLlmViQmaU96p+IDTd7GXFFzw/pThd8Fm\nBa4+xA8CrOCwFvj4XGYUfw11px6Mzwzy5SVxVmrFY2Sl8kUMX7p/dAe5AY+2x3Qc\nje7s9d/w/yz3Z2s0H358hXFt6lulT9jzzcXLnK+6EDkoFxNiJaRfHA+eeWS5tBHi\nbbBES8M0nf7TwQ5lT79uGCVqhLCESSM2R54uyNLQqTZJmnEKOrgpW4aQ1xagIy/G\nur39fIfBMq36vKavmPnZLhKZO5F/TR7AS2lbFvx7dC/OzjUmwCELNF4h5H/3Qgwf\nYq2oyBgYlntd36W/KJ+U4/Pi1n42nUAg9ALvyC9Wlroa3n7PzVO1AIi9GztIrYTp\nJGc3voNS0OfCSCzLax/c+WnbZzBq4ki2qPoMAQkfFuf41BBEMqC8ugfa558Iu450\nJa2+OXGOLIQIS0OcUI3qjwn36DKy5LTM0Tu3d5cwgMIyZX2HEf8paKBnuknouZQf\nepKzMpP8u8/iwbrCusk6i8Ko3mzzV7HNNvLb4NArb/d0Hqo3MulftU/owLt+nJkR\nibeRGdZb6hm23bds01Psj0YTIP4kDX/+b7wPsb36zk5vFqxAid8U2CvDvQAohjAK\nkxJkKZD270DB2wggGPGmNFryA1dJMIEJdefvFHEUtaymEjd/AZJCywKPNfJdZOoH\n70OISV9bwjj0be8bSliZCKAEFgPlXGxyuqHGXSLguw0Br5lT40ucvQldTQDYQEFy\n9EV1uF8iteLvKoFRR9u4k2zjfVmc7H5+1Gh3jvKIRZOsuL+lLVbmF0AVNJ1ec3eT\nxYLvPKe5qYA+/ZuPhLzgz9UDH+fYVloHjugvwZFTP8sNrFUYwlHNOqz0HzZ4cxrh\nHuIDKu91cFEpLllgwnD93Y6V5OAdFglJ+7WOhIZVQks9ss40SnykWLOOp+ERs4Mw\nEmPdCg4EtrWCgCc40cMdX/E0BvYj45QDc+Qm/iBH1QREUaN1N2wWkKyBKFeH1nn+\nGXDe24GAidnGY6T0ilndxA/8WK4xnrqvCupToqzFSQXG0/AlrTquzvv4Ze6qy//B\nOnPe5R7TP7Y5VgpYuZKIMrO6/7awiGaQTX01Hj3m+QfkKpYcy+jyolSEiSkLka5f\nSX3cVeq0QNrEX6B1rhj1MTIc/97qJ5nuEuvAvX+45P7ozYvYMbS/9CRlHmLyjzCZ\nUXKH8ATJv5BWC+QPTw5ESNJUwIOXNDFJKtdOv0WpiOtKRE8g+5D4+5en8u4zb3x4\n-----END RSA PRIVATE KEY-----" > ~/.ssh/id_rsa
  - echo -e "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC+9aPp9vTGwAPLWErmcoDN7gawnyOGW9aSgrwh3ffJqjxpPgeX7OrL6Dr/Gb+nNuglDnkhN2eOXLvBSrPMY8kKqRKzpZ75zi3IQKn2ryGSJ4oroKxf40if72C6CwJD/ZDm6QLrAA/KuMiPw25K2aXvc+YrT+8xk17VXmIa8yIMAjLOxytoHySgiIrmodhhKTSZ86JSffVgkxzB4ZP4BvTS+Rx8S+43PYQvdYaBwbESRBEC7YfLoNPRmLIQai9bTWZj+jc5mDcd7mQJUQRjTclOeSpjdSf9nq70usi8n3W9lTAxWgcCVOOAmhsVjFu2o42+GMzP6qx2Dnz1bSH1dkyR anthony@anthony-UX510UWK" > ~/.ssh/id_rsa.pub
  - echo $id_rsa
  - sudo chmod 600 ~/.ssh/*
  - sudo chmod 644 ~/.ssh/config
  - cat -e ~/.ssh/id_rsa.pub
  - cat -e ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa.pub
  - cat ~/.ssh/id_rsa
  - eval `ssh-agent -s`
#  - ssh-keygen -p -P $passphrase -N "" -f ~/.ssh/id_rsa
  - ssh-add ~/.ssh/id_rsa
#  - sshpass -p "$passphrase" ssh-add ~/.ssh/id_rsa
#  - sudo service ssh restart
  - mysql -uroot -e "create database dropshippers;"
  - mysql -uroot -e "CREATE USER 'dropshippers'@'localhost' IDENTIFIED BY 'p@ssword';"
  - mysql -uroot -e "GRANT ALL ON dropshippers.* To 'dropshippers'@'localhost';"
  - sudo apt-add-repository ppa:ansible/ansible -y
  - sudo apt-get update -qq
  - sudo apt-get install -y ansible

install:
  - composer install
  - bin/console doctrine:schema:update --force
  - bin/console doctrine:fixtures:load --no-interaction
  - ansible-playbook ./ansible/playbook.yml -i ./ansible/production --syntax-check
  - ansible-playbook ./ansible/playbook.yml -i ./ansible/production --user=anthony
