language: php
php:
    - 7.1
services:
    - mysql
before_install:
    - echo "hello first test !"
    - mysql -uroot -e "create database dropshippers;"
    - mysql -uroot -e "CREATE USER 'dropshippers'@'localhost' IDENTIFIED BY 'P@ssword';"
    - mysql -uroot -e "GRANT ALL ON dropshippers.* To 'dropshippers'@'localhost';"
    - sudo apt-get update -qq
    - sudo apt-get install software-properties-common
    - sudo apt-add-repository ppa:ansible/ansible -y
    - sudo apt-get update -qq
    - sudo apt-get install -y ansible
    - ./.ssh/known_hosts << '|1|cI5fNGd45quKjD0aIdH8RJVk5rw=|vgbJQ/hvE2QcmTRpAMthbj+mg2k= ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBG4WvDXnP33VY7BqTDUReBz2LV4yKAf59nS4KDRSAdRmaYsFoiXTqAFlrl9MJk2rjhwhTDOYl6UujEWHlAuX2+c='

install:
    - composer install
    - bin/console doctrine:schema:update --force
    - bin/console doctrine:fixtures:load --no-interaction
    - ansible-playbook ./ansible/playbook.yml -i ./ansible/production --syntax-check