language: php

php:
  - 7.1

services:
  - mysql

addons:
  ssh_known_hosts:
    - 46.101.119.131

notifications:
  email: false

branches:
  only:
    - master

before_install:
  - echo "hello first test !"
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common sshpass
  - sudo rm /etc/ssh/ssh_config
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  - echo -e "$id_rsa_pub" > ~/.ssh/id_rsa.pub
  - echo -e "$id_rsa" > ~/.ssh/id_rsa
  - sudo chmod 600 ~/.ssh/*
  - sudo chmod 644 ~/.ssh/config
#  - cat ~/.ssh/id_rsa.pub
#  - cat ~/.ssh/id_rsa
  - eval `ssh-agent -s`
  - ssh-keygen -p -P $passphrase -N "" -f ~/.ssh/id_rsa
  - ssh-add ~/.ssh/id_rsa
  - mysql -uroot -e "create database dropshippers;"
  - mysql -uroot -e "CREATE USER 'dropshippers'@'localhost' IDENTIFIED BY 'p@ssword';"
  - mysql -uroot -e "GRANT ALL ON dropshippers.* To 'dropshippers'@'localhost';"
  - sudo apt-add-repository ppa:ansible/ansible -y
  - sudo apt-get update -qq
  - sudo apt-get install -y ansible

install:
  - composer install
  - bin/console doctrine:schema:update --force
  - bin/console doctrine:fixtures:load --no-interaction
  - ansible-playbook ./ansible/playbook.yml -i ./ansible/production --syntax-check
  - ansible-playbook ./ansible/playbook.yml -i ./ansible/production --user=anthony

#deploy:
#  provider: script
#  script: scripts/deploy.sh
#  on:
#    branch: master
