language: php

php:
  - 7.1

services:
  - mysql

addons:
  ssh_known_hosts:
    - 46.101.119.131

notifications:
  email: false

before_install:
  - echo "hello first test !"
  - sudo apt-get update -qq
  - sudo apt-get install software-properties-common sshpass
  - sudo rm /etc/ssh/ssh_config
  - sudo cp ansible/roles/dropshippers/templates/ssh_config /etc/ssh/ssh_config
  - sudo cat /etc/ssh/ssh_config
  - sudo cat ~/.ssh/config
  - echo -e "Host *\n\tStrictHostKeyChecking no\n" > ~/.ssh/config
  - echo -e "$id_rsa.pub" > ~/.ssh/id_rsa.pub
  - echo -e "$id_rsa" > ~/.ssh/id_rsa
  - echo $id_rsa
  - sudo chmod 600 ~/.ssh/*
  - sudo chmod 644 ~/.ssh/config
  - cat -e ~/.ssh/id_rsa.pub
  - cat -e ~/.ssh/id_rsa
  - cat ~/.ssh/id_rsa.pub
  - cat ~/.ssh/id_rsa
  - eval `ssh-agent -s`
#  - ssh-keygen -p -P $passphrase -N "" -f ~/.ssh/id_rsa
  - ssh-add ~/.ssh/id_rsa
#  - sshpass -p "$passphrase" ssh-add ~/.ssh/id_rsa
#  - sudo service ssh restart
  - mysql -uroot -e "create database dropshippers;"
  - mysql -uroot -e "CREATE USER 'dropshippers'@'localhost' IDENTIFIED BY 'p@ssword';"
  - mysql -uroot -e "GRANT ALL ON dropshippers.* To 'dropshippers'@'localhost';"
  - sudo apt-add-repository ppa:ansible/ansible -y
  - sudo apt-get update -qq
  - sudo apt-get install -y ansible

install:
  - composer install
  - bin/console doctrine:schema:update --force
  - bin/console doctrine:fixtures:load --no-interaction
  - ansible-playbook ./ansible/playbook.yml -i ./ansible/production --syntax-check
  - ansible-playbook ./ansible/playbook.yml -i ./ansible/production --user=anthony
