language: php
php:
    - 5.6
    - 7.1
services:
    - mysql
before_install:
    - echo "hello first test !"
    - mysql -e 'CREATE DATABASE dropshippers;'
    - mysql -e 'CREATE USER `dropshippers`@`localhost` IDENTIFIED BY 'P@ssword';'

install:
    - composer install