<?php

namespace Dropshippers\APIBundle\Repository;

/**
 * CategoryLocaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryLocaleRepository extends \Doctrine\ORM\EntityRepository
{
}
