<?php

namespace Dropshippers\APIBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * CategoryLocaleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryLocaleRepository extends EntityRepository
{
    public function checkLocaleExists($locale)
    {
        //we check if there is an existing traduction in this language
        $result = $this->findBy(["language" => $locale]);

        if (!$result){
            return false;
        } else {
            return true;
        }
    }
}
