<?php

namespace Dropshippers\APIBundle\Repository;

/**
 * ds_local_product_categoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ds_local_product_categoryRepository extends \Doctrine\ORM\EntityRepository
{
}
