<?php

namespace Dropshippers\APIBundle\Repository;

/**
 * ds_local_ps_productRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ds_local_ps_productRepository extends \Doctrine\ORM\EntityRepository
{
}
