<?php

namespace Dropshippers\APIBundle\Repository;

/**
 * ds_product_requestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ds_product_requestRepository extends \Doctrine\ORM\EntityRepository
{
}
