<?php

namespace Dropshippers\APIBundle\Repository;

/**
 * ds_product_tagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ds_product_tagRepository extends \Doctrine\ORM\EntityRepository
{
}
