<?php

namespace Dropshippers\APIBundle\Repository;

/**
 * ds_request_messageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ds_request_messageRepository extends \Doctrine\ORM\EntityRepository
{
}
