<?php

namespace Dropshippers\APIBundle\Repository;

/**
 * ds_shopRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ds_shopRepository extends \Doctrine\ORM\EntityRepository
{
}
