<?php

namespace Dropshippers\APIBundle\Repository;

/**
 * ds_tax_groupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ds_tax_groupRepository extends \Doctrine\ORM\EntityRepository
{
}
