<?php

namespace Dropshippers\APIBundle\Repository;

/**
 * LangRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LangRepository extends \Doctrine\ORM\EntityRepository
{
}
