<?php

namespace Dropshippers\APIBundle\Repository;

/**
 * LocalProductCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalProductCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
