<?php

namespace Dropshippers\APIBundle\Repository;

/**
 * LocalManufacturerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalManufacturerRepository extends \Doctrine\ORM\EntityRepository
{
}
