<?php

namespace Dropshippers\APIBundle\Repository;

/**
 * LocalPsProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalPsProductRepository extends \Doctrine\ORM\EntityRepository
{
}
