<?php

namespace Dropshippers\APIBundle\Repository;

/**
 * LocalProductTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalProductTagRepository extends \Doctrine\ORM\EntityRepository
{
}
