<?php

namespace Dropshippers\APIBundle\Repository;

/**
 * LocalPsTaxGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalPsTaxGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
