<?php

namespace Dropshippers\APIBundle\Repository;

/**
 * LocalProductImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocalProductImageRepository extends \Doctrine\ORM\EntityRepository
{
}
