<?php

namespace Dropshippers\APIBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ManageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ManageRepository extends EntityRepository
{
}
