<?php

namespace Dropshippers\APIBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PartnershipRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartnershipRequestRepository extends EntityRepository
{
}
