<?php

namespace Dropshippers\APIBundle\Repository;

/**
 * ProductRequestMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRequestMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
