<?php

namespace Dropshippers\APIBundle\Repository;

/**
 * ProductRequestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRequestRepository extends \Doctrine\ORM\EntityRepository
{
}
