<?php

namespace Dropshippers\APIBundle\Repository;

/**
 * RequestMessageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequestMessageRepository extends \Doctrine\ORM\EntityRepository
{
}
