<?php

namespace Dropshippers\APIBundle\Repository;

/**
 * ShopTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ShopTagRepository extends \Doctrine\ORM\EntityRepository
{
}
