<?php

namespace Dropshippers\APIBundle\Repository;

/**
 * TaxGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TaxGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
