services:
    dropshippers_api.prestashop16:
        class: Dropshippers\APIBundle\Services\Prestashop16Service
        arguments: [ '@doctrine' ]
    dropshippers_api.authentication:
        class: Dropshippers\APIBundle\Services\AuthenticationService
        arguments: [ '@doctrine' ]
    dropshippers_api.front:
        class: Dropshippers\APIBundle\Services\FrontService
        arguments: [ '@doctrine', '@dropshippers_api.category']
    dropshippers_api.category:
        class: Dropshippers\APIBundle\Services\CategoryService
        arguments: [ '@doctrine' ]
    dropshippers_api.helper:
        class: Dropshippers\APIBundle\Services\HelperService
    dropshippers_api.zone:
        class: Dropshippers\APIBundle\Services\ZoneService
        arguments: [ '@doctrine' ]