services:
#    kernel.listener.your_listener_name:
#        class: Dropshippers\APIBundle\EventListener\ResponseListener
#        tags:
#            - { name: kernel.event_listener, event: kernel.response, method: onKernelResponse }
    dropshippers_api.prestashop16:
        class: Dropshippers\APIBundle\Services\Prestashop16Service
        arguments: [ '@doctrine' ]
    dropshippers_api.authentication:
        class: Dropshippers\APIBundle\Services\AuthenticationService
        arguments: [ '@doctrine' ]
    dropshippers_api.front:
        class: Dropshippers\APIBundle\Services\FrontService
        arguments: [ '@doctrine' ]
    dropshippers_api.category:
        class: Dropshippers\APIBundle\Services\CategoryService
        arguments: [ '@doctrine' ]